/* Loomi.AI design tokens — applied to every page. */
tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#000000",
        "on-primary": "#ffffff",
        "background": "#f9f9f9",
        "on-background": "#1a1c1c",
        "surface": "#f9f9f9",
        "surface-bright": "#f9f9f9",
        "surface-container": "#eeeeee",
        "surface-container-low": "#f3f3f4",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2",
        "surface-variant": "#e2e2e2",
        "outline": "#76777d",
        "outline-variant": "#c6c6cd",
        "on-surface": "#1a1c1c",
        "on-surface-variant": "#45464d",
        "secondary": "#5c5f60",
        "secondary-container": "#e1e3e4",
        "on-secondary-container": "#626566",
        "tertiary-fixed": "#6ffbbe",
        "tertiary-fixed-dim": "#4edea3",
        "on-tertiary-fixed": "#002113",
        "on-tertiary-container": "#009668",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "gain": "#10B981",
        "loss": "#EF4444",
      },
      borderRadius: { DEFAULT: "0.25rem", lg: "0.5rem", xl: "0.75rem", full: "9999px" },
      spacing: {
        gutter: "24px", sm: "12px", margin: "32px", xl: "64px", lg: "40px",
        xs: "4px", md: "24px", base: "8px",
      },
      fontFamily: {
        "headline-md": ["Sora"], "headline-lg": ["Sora"],
        "label-md": ["Sora"], "label-sm": ["Sora"],
        "data-mono": ["Inter"], "body-md": ["Inter"], "body-lg": ["Inter"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["40px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-md":    ["14px", { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-sm":    ["12px", { lineHeight: "1",   letterSpacing: "0.04em", fontWeight: "600" }],
        "data-mono":   ["14px", { lineHeight: "1",   letterSpacing: "-0.01em", fontWeight: "500" }],
        "body-md":     ["16px", { lineHeight: "1.5", letterSpacing: "0em",    fontWeight: "400" }],
      },
    },
  },
};
